env:
  es6: true
  browser: true
  commonjs: true

extends: ['airbnb-base', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'
  import/resolver: {
    typescript: {}
  }

rules:
  comma-dangle:
    - warn
    - always-multiline
  import/extensions: 'off'
